### PR TITLE
Complete Nvidia switch to intel

### PR DESCRIPTION
**Pull request by JeffLabonte**
This commit change path to keep it clean with the other conf files in cmdline.d. Add nouveau.modeset=0 to prevent issues some user could encounter ( Nouveau doesn't always play nice with newer Nvidia GPU i.e GTX 1050 )

### CODE REVIEW

**Comment by JeffLabonte** [comment]
Add changes to README.md and add gitignore for VIM metadata

**Comment by MarechalLima** [comment]
https://nouveau.freedesktop.org/wiki/KernelModuleParameters/

**Comment by JeffLabonte** [comment]
Why do you want to keep nouveau?

**Comment by JeffLabonte** [comment]
How can you tell? If I use xrandr --list-providers all I see is the Intel GPU

**Comment by MarechalLima** [comment]
it is estimated by battery level, without nouveau driver the Nvidia isn't used, but it remains on.

**Comment by MarechalLima** [comment]
Other way do turn Nvidia off is using bbswitch, which is used by bumblebee.

**Comment by MarechalLima** [comment]
But I've been working on a version with bbswitch, I will be merging the code soon.

**Comment by MarechalLima** [comment]
Merged, and the Nvidia driver disables nouveau when installing. /usr/lib/modprobe.d/nvidia.conf must be: blacklist nouveau

**Comment by JeffLabonte** [comment]
Well if you need a hand at some points! I would be glad to help!

**Comment by MarechalLima** [comment]
Thanks, Could you tell me if blacklisting nouveau is enough to avoid problems on new cards or kernel parameters are also necessary?

**Pull request merged**
